server:
  port: 80
#配置redis
spring:
  application:
    name: webui
  redis:
    host: 192.168.65.166
    jedis:
      pool:
        max-idle: 100
  #配置redis缓存session
  session:
    store-type: redis
  #配置thymeleaf前后缀
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
  instance:
    prefer-ip-address: true
    
oss.project.parent.folder: project
oss.endpoint: http://oss-cn-shenzhen.aliyuncs.com
oss.accessKeyId: LTAIrqGntiJOzAhB
oss.accessKeySecret: TCBmjvGE3NMViRPimKbElRETiBZRQd
oss.bucketName: zay-crowd-001
oss.bucket.domain: http://zay-crowd-001.oss-cn-shenzhen.aliyuncs.com

#应用的appID
alipay.app_id: 2016092500596596
alipay.merchant_private_key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCS2e5KKbZ9IUSzXqOtll6D8z0Da759Nr/3MLPYchjaP8rVhEWxfRJ22bmLUACYfBYvXetZd1SfWaHvPWmsoD3WgoPyxOlK8LwA6Gc764sqNPcx0eOfyTWkgs0qvEc68waM1aqDO2qedi8Wlhy27uWey19TiPzR9uCWsSvhBM/no2ZADEgo9wmDmhiDEiZ3jtof5eRewjXF/KlQ5lLZQ4dkdaOaGUO1iS1P7lyHUflSAtQGt16EB7fA48L3XPmRycpVlhEoRggAPoUonc+Jw/cPw72ZNRq35Ycdcuezcz++BZDlZ39dJ6fuP0wBD2aMJMTcT8GFLp6rs5wEcbnwy4SpAgMBAAECggEAEMBzglpHyvZkk+GT4lVo6rxwlVdRH4+DTntryKEbXKoyRTEVki2mUZB8rfuuVbayAS1Bj68hJBxhcJ0c1OhipXm1+5ei1T2o9KGORTOVaHcqS7CZuryFNgMFzH410e+vK5mkHdxFSVZKANWW6PdPklG4yhqyXHFBJW+Ihd66qL26fYcekvz/guM0FeSjlxF3UiYF0J+ptdYg0C8Vg7eIfyLbTfnv2IklmJoAg2lioQYjB3uBYZDYfyd28xHI6AfoPXyNWVWsrYKoV17btBGesBHMKdH4UObq6aBG8T3whA+FhrhgGM/EmJQfdm8Oo4FHzNmm8A3C0EMBYBocFVOCAQKBgQDaEhG993+qWm82QQ7Tj4GrM5dhjE8nr0Dd3yunQmWsTNHJTItTjmht3RWx+QY0V3jCS9++LwHy3Go8CXWyHXmRmcP0Lfa1nbPK9GZivpb/+Tt5GAPFkBhRYOMLddYFbvCcfs32h0CStTWvDApl2sP68WBE1TtIx7PpONA3blNVeQKBgQCsZLZTDvbOhc3qTThH9XBE2gsfSj+/am3EYSi8wHhaP2JL9fyvjfWqbp0ur2DLD1UyRg4/l+zoGB1F6wB7lBAcDxKHnTPby581rtVijrnQiofZRNolQQfXEg9ch/WmuNKbJ802nKc0tuPOuiwjzo5JgJiEb6/Y5zlOsyFvWlnMsQKBgA8011vh2FsutzaXTstd5HLlxBafTB2+UM2n9ElTjfd32+Enn0eSVKHkmtCwRsh7mQYjeFSwvngK+rV5C2YCPCn1CP8L/XoopxLt+/3CwJDU9lq5W/n41FlIYky4SNZUKB8hkIcyY0RXsoikVE1J9gSXtFjYbavjkR4gQhS7csAxAoGAMVZRZ8vsjoZ0vA2FgfKYQtw0OqxBOkL3TzCPPBXJW+qv8xVfT87M9A3cJjRC+1pUA6NRCJouTu430n7DEJr7UUxu/SjcYpcP5Yk3wJEgVLKQ1nmCBQ9rcv3UL6MphqF2hLkLXgnPQKLm548YetbumdKX068zIFxsZj2V4Ax3jsECgYAZiYSZYF0w6P0bIfowl3XUCJcwD+at/dKCGdHQhNgOC4qfMwSfqkEqAWiXmsRLi9yyFiaS8Ty6cQvAvEkgRjSNvDe9hrZUriruXur45C4l/gXq8Z5R38zOWwK8fsC3kRDao/twORG0+xoAN11osWh8nrAZOTRbTB/LDdYvTqUlxw==+jvJK0tlZmolJCOyVbWIfj8o4APiimRRupoYBhvLObz+KJ2L9+kXPHQrOXMIJyFKDYN/tRGHlcgty5pBvl9zC6Oz/xF4PrSSDGz33SbsxurZKkPrdt+V2jlyRCMkFDiOTSmbmM6Q1kdp/yT4zK5igAV3K8LgmxgrsPOV3PsGvQTGVSFbrrEUvEAYJ7EK9G6aXBy+xBDaxrM33Lb8q3wVRwnpnZ1DcgH4fTSlI4fhJmCxZzp6peg22QTAgMBAAECggEAYBlrFNySNWFBQGO/YiiamzdCjOXNMYRMbJWiy8cT3o/EpW4HS3L41rZbGz19c/9sR8zPFFZCBTaH9DroEy+ZJNBloha/3N/8nZJGrgwoT3IsujyrOiwv4wqKjSpnhdStse4zUOICAMo7Z55o26EH5yT5aHfQSRtRuFAhiBvTW8yUu6K+COXJfGGhC95DhyIokUkAHWAFKtwCpdzMONaq4X8RgHy17Qf0FOo8elIaJ8A/pYDcENaCf7cWtZKocT43f4MVH4/O4d6rqgSG3KiVW8zu9yo+D1qVFsAlJLFGFop66iQ5CRklumt/cWUsUkTFtOyIotDrDotDHdJIvq+xaQKBgQC/9dln2y3yER2BBUYWgmK0zVr9xzYsyqw1PFl+1S9PWupt8jBJJwFJzUy0XhblfwpjzqpVEqpdtFjYEdYmT9EwFjcQCBqjYn1L6RjJUJnBgk51vdOfoNomo/Tf5gu69TuR7sl6y5vS8i/5BazZTjJeNf/KgMCavVTJCuDxninblwKBgQCxtfjBH6XrlBPZ/r0d1q1IUfH5CQQ5NumM3d4dKOI6fBab+cORJNXcpDMnkE/7NiwoKEVaaskEwnNuTaM01icMPkS1tXJg/AU64KMBHZUXAf/ANwmnvjOZ0GHoNmHgxFEA82fJVfg3PqG7Cvxkm42rm45b2rqJ5wFK/CpbC9x65QKBgBdt62Yos1frTN2VhjNzIJcOxX9aFDutVQ1+WzIG1SprX1eiCtCy6Q5X93fAUC0cr2j1LYcKqy6at4lPzAKLFW44F+pmAtJUUBS206amps2emPL4A19lY5r5wgad7mqYSfgK3B6XwWIi20YasjknuTAUiS7vPhLk7vdG06PJ+TPrAoGAXQb4UAiEL70VY0GBuFP/4+LZu1bn+hdvzQj70+HqA1mf8EigAqP4vAbMrIJUDBpApUjnfTx3PGGaUXyc2fTc/gC+sSxp0rE6/6ZGTjgxKpkmS3XEPSZJFtTJ2+hT9nhuOwQwKWoyhKDpwuMuWnA/ijzlGdp3WecuexVkCsM7yK0CgYBTUw2CZZy0JgJBS3O/SUe3HqhywKSFXkFrPaF8jj9B4wFkJHKb4EKcIV+12IcFqV3++rSpF6ZTibz0jhIA2nzMtuP5Kij4Vq3ISKjyx01NQqmdE3x6f8/nirLfVfciSCDvaiIFF1cMhsk+t/jScCwGkk88xhrhrIKJ9klAmgN2LQ==
alipay.alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxzzZ6WmkCBUpgPHZ3RiktoWrsu08rx+PYm1zhnyevBsyIm/VRkI3M+fUEZd0lcEFA4CQMg6Q+DQKUIbvjGRqWqgc4BA75gP+A4A9ZCnJIjBss7u48GCUiqdEjnLdhz0Xx4euGpPOAA8oySfVNF6ne2rjLhGB0EqcBDdWn/QJN0k7ZY4OqfGxwWy0tqCDMoGd8njPWTmUqs9Wyquf1Q/hqhM7L/fzLXqrE6V/kuRsTU2tJ3CxqSrFntTUE7qn6JwFCP4VfwYg8hkKWDipPJUk79hOUmSbIlw1Vgg8e7CGaQHCr3YUgaqmiq2vGeplU/SMocsUC5lpB2ym+CQyS/rUWQIDAQAB
alipay.notify_url: http://remr3m.natappfree.cc/pay/notify
alipay.return_url: http://remr3m.natappfree.cc/pay/return
alipay.sign_type: RSA2
alipay.charset: utf-8
alipay.gatewayUrl: https://openapi.alipaydev.com/gateway.do


